CREATE TABLE IF NOT EXISTS TB_CLIENTES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_PRODUTOS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    descricao VARCHAR(100) NOT NULL,
    preco_unitario DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_PEDIDOS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_cliente INTEGER NOT NULL,
    num_pedido VARCHAR(20) NOT NULL UNIQUE,
    data_pedido DATETIME NOT NULL,
    FOREIGN KEY (id_cliente) REFERENCES TB_CLIENTES(id)
);

CREATE TABLE IF NOT EXISTS TB_ITENS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_pedido INTEGER NOT NULL,
    id_produto INTEGER NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_venda DOUBLE NOT NULL,
    FOREIGN KEY (id_pedido) REFERENCES TB_PEDIDOS(id),
    FOREIGN KEY (id_produto) REFERENCES TB_PRODUTOS(id)
);